name: atithi_bhavan_mobile
description: "A guest room booking application."
# Prevent accidental publishing to pub.dev.
publish_to: 'none' 

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

# --- DEPENDENCIES ---
# This is where you list all the packages your app needs to run.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

  # Package for creating PDF documents.
  pdf: ^3.10.8
  http: ^1.2.1

  # Package for displaying and printing PDF documents.
  printing: ^5.12.0

  # Package for internationalization and date formatting.
  intl: ^0.19.0
  flutter_dotenv: ^5.0.2


# --- DEV DEPENDENCIES ---
# These packages are only used for development and testing.
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  # --- ADD THIS LINE ---
  flutter_launcher_icons: ^0.13.1

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices.
  

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # This is the correct way to declare the entire folder.
  # The 'a' in 'assets' must align with the 'u' in 'uses-material-design'.
  assets:
    - assets/
    - .env.development

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
 # This line makes the whole folder available

  fonts:
    - family: BodoniModa
      fonts:
        - asset: fonts/BodoniModa-VariableFont_opsz,wght.ttf
  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21 # Your app's minimum Android version  